blueprint:
  name: ROBB SMARRT 8-button switch (ROB_200-007-0) - Fixed
  description: |
    Control devices with ROBB SMARRT 8-button ZigBee switch
    Fixed to properly handle Move/Stop events for dimming
  domain: automation
  input:
    remote:
      name: ROBB SMARRT switch
      description: Select the switch device
      selector:
        device:
          filter:
            - integration: zha
              model: ROB_200-007-0
            - integration: zha
              model: ROB_200-025-0
          multiple: false
    
    on_button_1_short:
      name: Button 1 ON - Short press
      description: Action to run on short press
      default: []
      selector:
        action: {}
    
    off_button_1_short:
      name: Button 1 OFF - Short press
      description: Action to run on short press
      default: []
      selector:
        action: {}
    
    on_button_1_long:
      name: Button 1 ON - Long press (hold)
      description: Action to run while holding (repeat until released)
      default: []
      selector:
        action: {}
    
    off_button_1_long:
      name: Button 1 OFF - Long press (hold)
      description: Action to run while holding (repeat until released)
      default: []
      selector:
        action: {}
    
    on_button_2_short:
      name: Button 2 ON - Short press
      default: []
      selector:
        action: {}
    
    off_button_2_short:
      name: Button 2 OFF - Short press
      default: []
      selector:
        action: {}
    
    on_button_2_long:
      name: Button 2 ON - Long press
      default: []
      selector:
        action: {}
    
    off_button_2_long:
      name: Button 2 OFF - Long press
      default: []
      selector:
        action: {}
    
    on_button_3_short:
      name: Button 3 ON - Short press
      default: []
      selector:
        action: {}
    
    off_button_3_short:
      name: Button 3 OFF - Short press
      default: []
      selector:
        action: {}
    
    on_button_3_long:
      name: Button 3 ON - Long press
      default: []
      selector:
        action: {}
    
    off_button_3_long:
      name: Button 3 OFF - Long press
      default: []
      selector:
        action: {}
    
    on_button_4_short:
      name: Button 4 ON - Short press
      default: []
      selector:
        action: {}
    
    off_button_4_short:
      name: Button 4 OFF - Short press
      default: []
      selector:
        action: {}
    
    on_button_4_long:
      name: Button 4 ON - Long press
      default: []
      selector:
        action: {}
    
    off_button_4_long:
      name: Button 4 OFF - Long press
      default: []
      selector:
        action: {}

    hold_repeat_ms:
      name: Hold repeat interval (ms)
      description: Delay between repeated actions while holding a button
      default: 200
      selector:
        number:
          min: 50
          max: 1000
          step: 10
          mode: slider

mode: restart
max_exceeded: silent

variables:
  command: '{{ trigger.event.data.command }}'
  endpoint: '{{ trigger.event.data.endpoint_id | int }}'
  move_mode: '{{ trigger.event.data.params.move_mode | int(-1) }}'
  remote_device_id: !input remote

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - choose:
      # Button 1 ON short
      - conditions:
          - condition: template
            value_template: '{{ command == "on" and endpoint == 1 }}'
        sequence: !input on_button_1_short
      
      # Button 1 OFF short
      - conditions:
          - condition: template
            value_template: '{{ command == "off" and endpoint == 1 }}'
        sequence: !input off_button_1_short
      
      # Button 1 ON long (move_with_on_off up)
      - conditions:
          - condition: template
            value_template: '{{ command == "move_with_on_off" and endpoint == 1 and move_mode == 0 }}'
        sequence:
          - repeat:
              until:
                - condition: template
                  value_template: >-
                    {{
                      wait.trigger is not none
                      and wait.trigger.event.data.device_id == remote_device_id
                      and (wait.trigger.event.data.endpoint_id | int) == endpoint
                      and wait.trigger.event.data.command in ['stop', 'stop_with_on_off']
                    }}
              sequence:
                - choose:
                    - conditions: []
                      sequence: !input on_button_1_long
                - wait_for_trigger:
                    - platform: event
                      event_type: zha_event
                      event_data:
                        device_id: !input remote
                        endpoint_id: 1
                        command: stop
                    - platform: event
                      event_type: zha_event
                      event_data:
                        device_id: !input remote
                        endpoint_id: 1
                        command: stop_with_on_off
                  timeout:
                    milliseconds: !input hold_repeat_ms
                  continue_on_timeout: true
      
      # Button 1 OFF long (move down)
      - conditions:
          - condition: template
            value_template: '{{ command == "move" and endpoint == 1 and move_mode == 1 }}'
        sequence:
          - repeat:
              until:
                - condition: template
                  value_template: >-
                    {{
                      wait.trigger is not none
                      and wait.trigger.event.data.device_id == remote_device_id
                      and (wait.trigger.event.data.endpoint_id | int) == endpoint
                      and wait.trigger.event.data.command in ['stop', 'stop_with_on_off']
                    }}
              sequence:
                - choose:
                    - conditions: []
                      sequence: !input off_button_1_long
                - wait_for_trigger:
                    - platform: event
                      event_type: zha_event
                      event_data:
                        device_id: !input remote
                        endpoint_id: 1
                        command: stop
                    - platform: event
                      event_type: zha_event
                      event_data:
                        device_id: !input remote
                        endpoint_id: 1
                        command: stop_with_on_off
                  timeout:
                    milliseconds: !input hold_repeat_ms
                  continue_on_timeout: true
      
      # Button 1 Stop (release) - handles both stop and stop_with_on_off
      - conditions:
          - condition: template
            value_template: '{{ (command == "stop" or command == "stop_with_on_off") and endpoint == 1 }}'
        sequence: []
      
      # Button 2 ON short
      - conditions:
          - condition: template
            value_template: '{{ command == "on" and endpoint == 2 }}'
        sequence: !input on_button_2_short
      
      # Button 2 OFF short
      - conditions:
          - condition: template
            value_template: '{{ command == "off" and endpoint == 2 }}'
        sequence: !input off_button_2_short
      
      # Button 2 ON long
      - conditions:
          - condition: template
            value_template: '{{ command == "move_with_on_off" and endpoint == 2 and move_mode == 0 }}'
        sequence:
          - repeat:
              until:
                - condition: template
                  value_template: >-
                    {{
                      wait.trigger is not none
                      and wait.trigger.event.data.device_id == remote_device_id
                      and (wait.trigger.event.data.endpoint_id | int) == endpoint
                      and wait.trigger.event.data.command in ['stop', 'stop_with_on_off']
                    }}
              sequence:
                - choose:
                    - conditions: []
                      sequence: !input on_button_2_long
                - wait_for_trigger:
                    - platform: event
                      event_type: zha_event
                      event_data:
                        device_id: !input remote
                        endpoint_id: 2
                        command: stop
                    - platform: event
                      event_type: zha_event
                      event_data:
                        device_id: !input remote
                        endpoint_id: 2
                        command: stop_with_on_off
                  timeout:
                    milliseconds: !input hold_repeat_ms
                  continue_on_timeout: true
      
      # Button 2 OFF long
      - conditions:
          - condition: template
            value_template: '{{ command == "move" and endpoint == 2 and move_mode == 1 }}'
        sequence:
          - repeat:
              until:
                - condition: template
                  value_template: >-
                    {{
                      wait.trigger is not none
                      and wait.trigger.event.data.device_id == remote_device_id
                      and (wait.trigger.event.data.endpoint_id | int) == endpoint
                      and wait.trigger.event.data.command in ['stop', 'stop_with_on_off']
                    }}
              sequence:
                - choose:
                    - conditions: []
                      sequence: !input off_button_2_long
                - wait_for_trigger:
                    - platform: event
                      event_type: zha_event
                      event_data:
                        device_id: !input remote
                        endpoint_id: 2
                        command: stop
                    - platform: event
                      event_type: zha_event
                      event_data:
                        device_id: !input remote
                        endpoint_id: 2
                        command: stop_with_on_off
                  timeout:
                    milliseconds: !input hold_repeat_ms
                  continue_on_timeout: true
      
      # Button 2 Stop
      - conditions:
          - condition: template
            value_template: '{{ (command == "stop" or command == "stop_with_on_off") and endpoint == 2 }}'
        sequence: []
      
      # Button 3 ON short
      - conditions:
          - condition: template
            value_template: '{{ command == "on" and endpoint == 3 }}'
        sequence: !input on_button_3_short
      
      # Button 3 OFF short
      - conditions:
          - condition: template
            value_template: '{{ command == "off" and endpoint == 3 }}'
        sequence: !input off_button_3_short
      
      # Button 3 ON long
      - conditions:
          - condition: template
            value_template: '{{ command == "move_with_on_off" and endpoint == 3 and move_mode == 0 }}'
        sequence:
          - repeat:
              until:
                - condition: template
                  value_template: >-
                    {{
                      wait.trigger is not none
                      and wait.trigger.event.data.device_id == remote_device_id
                      and (wait.trigger.event.data.endpoint_id | int) == endpoint
                      and wait.trigger.event.data.command in ['stop', 'stop_with_on_off']
                    }}
              sequence:
                - choose:
                    - conditions: []
                      sequence: !input on_button_3_long
                - wait_for_trigger:
                    - platform: event
                      event_type: zha_event
                      event_data:
                        device_id: !input remote
                        endpoint_id: 3
                        command: stop
                    - platform: event
                      event_type: zha_event
                      event_data:
                        device_id: !input remote
                        endpoint_id: 3
                        command: stop_with_on_off
                  timeout:
                    milliseconds: !input hold_repeat_ms
                  continue_on_timeout: true
      
      # Button 3 OFF long
      - conditions:
          - condition: template
            value_template: '{{ command == "move" and endpoint == 3 and move_mode == 1 }}'
        sequence:
          - repeat:
              until:
                - condition: template
                  value_template: >-
                    {{
                      wait.trigger is not none
                      and wait.trigger.event.data.device_id == remote_device_id
                      and (wait.trigger.event.data.endpoint_id | int) == endpoint
                      and wait.trigger.event.data.command in ['stop', 'stop_with_on_off']
                    }}
              sequence:
                - choose:
                    - conditions: []
                      sequence: !input off_button_3_long
                - wait_for_trigger:
                    - platform: event
                      event_type: zha_event
                      event_data:
                        device_id: !input remote
                        endpoint_id: 3
                        command: stop
                    - platform: event
                      event_type: zha_event
                      event_data:
                        device_id: !input remote
                        endpoint_id: 3
                        command: stop_with_on_off
                  timeout:
                    milliseconds: !input hold_repeat_ms
                  continue_on_timeout: true
      
      # Button 3 Stop
      - conditions:
          - condition: template
            value_template: '{{ (command == "stop" or command == "stop_with_on_off") and endpoint == 3 }}'
        sequence: []
      
      # Button 4 ON short
      - conditions:
          - condition: template
            value_template: '{{ command == "on" and endpoint == 4 }}'
        sequence: !input on_button_4_short
      
      # Button 4 OFF short
      - conditions:
          - condition: template
            value_template: '{{ command == "off" and endpoint == 4 }}'
        sequence: !input off_button_4_short
      
      # Button 4 ON long
      - conditions:
          - condition: template
            value_template: '{{ command == "move_with_on_off" and endpoint == 4 and move_mode == 0 }}'
        sequence:
          - repeat:
              until:
                - condition: template
                  value_template: >-
                    {{
                      wait.trigger is not none
                      and wait.trigger.event.data.device_id == remote_device_id
                      and (wait.trigger.event.data.endpoint_id | int) == endpoint
                      and wait.trigger.event.data.command in ['stop', 'stop_with_on_off']
                    }}
              sequence:
                - choose:
                    - conditions: []
                      sequence: !input on_button_4_long
                - wait_for_trigger:
                    - platform: event
                      event_type: zha_event
                      event_data:
                        device_id: !input remote
                        endpoint_id: 4
                        command: stop
                    - platform: event
                      event_type: zha_event
                      event_data:
                        device_id: !input remote
                        endpoint_id: 4
                        command: stop_with_on_off
                  timeout:
                    milliseconds: !input hold_repeat_ms
                  continue_on_timeout: true
      
      # Button 4 OFF long
      - conditions:
          - condition: template
            value_template: '{{ command == "move" and endpoint == 4 and move_mode == 1 }}'
        sequence:
          - repeat:
              until:
                - condition: template
                  value_template: >-
                    {{
                      wait.trigger is not none
                      and wait.trigger.event.data.device_id == remote_device_id
                      and (wait.trigger.event.data.endpoint_id | int) == endpoint
                      and wait.trigger.event.data.command in ['stop', 'stop_with_on_off']
                    }}
              sequence:
                - choose:
                    - conditions: []
                      sequence: !input off_button_4_long
                - wait_for_trigger:
                    - platform: event
                      event_type: zha_event
                      event_data:
                        device_id: !input remote
                        endpoint_id: 4
                        command: stop
                    - platform: event
                      event_type: zha_event
                      event_data:
                        device_id: !input remote
                        endpoint_id: 4
                        command: stop_with_on_off
                  timeout:
                    milliseconds: !input hold_repeat_ms
                  continue_on_timeout: true
      
      # Button 4 Stop
      - conditions:
          - condition: template
            value_template: '{{ (command == "stop" or command == "stop_with_on_off") and endpoint == 4 }}'
        sequence: []
